### PR TITLE
Changed integers in bitwise arithmetic to hex

### PR DESCRIPTION
**Pull request by Kizby**
Changed most (all?) of the integer constants used in bitwise ANDs and
ORs to their hex representation to make them more transparent. Also
started making any progress at all grokking the internals of this mod :D

### CODE REVIEW

**Comment by CptSpaceToaster** [comment]
Looks pretty good... sadly, some of the numbers STILL look like junk, but that's just unavoidable with the spacing we chose.

Note, that the zeros in the compacted light integer (0BBBB 0GGGG 0RRRR 0LLLL) are there for optimization.  When you take one compacted integer, and subtract it from another compacted light integer, then you can check to see if there are any bits in the 0 positions, indicating that the second value had a color component that was greater than the first.

**Comment by CptSpaceToaster** [comment]
Resolved most of issue #5.  Closing it for now

**Comment by Kizby** [comment]
Err, did you mean to close the pull request or the issue?

**Comment by CptSpaceToaster** [comment]
I meant to close both, as this PR was able to cover most of the issues with #5.  Did I miss something?

**Comment by CptSpaceToaster** [comment]
Ahh I think I confused close terminology accidentally....

**Pull request merged**
