### PR TITLE
Added color information to debug menu

### PR DESCRIPTION
**Pull request by Kizby**
Changed the debug screen to actually show meaningful brightness numbers,
including the 0xRGB color value of the current block

### CODE REVIEW

**Comment by CptSpaceToaster** [comment]
I like this a lot.  I never had figured out where it took place though...thanks for finding it and making the change!

**Comment by Kizby** [comment]
It was kind of fun brushing up on my Java bytecode :) I don't think I've seen you on IRC the past couple days, at least if your IRC name is anything like your github name

**Comment by CptSpaceToaster** [comment]
I was on most of yesterday, but I've been working all today... email me if you need anything (and I'm not on IRC)

IRC: CptRageToaster

**Pull request merged**
